services:
  frontend:
    build: .
    container_name: raza-frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - autenticador_network

networks:
  autenticador_network:
    external: true