services:
  frontend:
    build:
      context: .
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    stdin_open: true
    tty: true
    networks:
      - autenticador_network

networks:
  autenticador_network:
    external: true